### ISSUE TITLE
Make index.html nicer

### ISSUE THREAD

**Issue by evanwaltersdev** [evanwaltersdev/videos-hacktoberfest#18]
index.html is looking a bit sad so feel free to make some chanages and PR

**Comment by shanejustice** [comment]
I'll like to try it.

**Comment by evanwaltersdev** [comment]
Sure thing go ahead!

**Comment by evanwaltersdev** [comment]
> Btw what type of changes are you looking for?

Maybe a simple colour change will be awesome! @Quantumf0x @shanejustice

**Comment by evanwaltersdev** [comment]
#47 Thanks @shanejustice it looks great
