### ISSUE TITLE
Edit 404.html

### ISSUE THREAD

**Issue by evanwaltersdev** [evanwaltersdev/videos-hacktoberfest#48]
Make the 404 page really awesome!

**Comment by m4tr1k** [comment]
@evanwaltersdev I can do it! But I will do it tomorrow. If anyone does a pull request about this before me, can I still do the pull request?

**Comment by evanwaltersdev** [comment]
@m4tr1k I will wait for you to submit your PR before I merge

**Comment by parthpandyappp** [comment]
I would like to contribute to this.

**Comment by MgowanoJr** [comment]
I would like to contribute to this

**Comment by PROTechThor** [comment]
I'll make a contribution as well.

**Comment by evanwaltersdev** [comment]
Merged #54 for now, feel free to keep pull requesting. The best one I will merge.

**Comment by MikeStrider** [comment]
I'll work on this.

**Comment by MikeStrider** [comment]
> I'll work on this.
Done, Pull Request submitted.
