### ISSUE TITLE
Footer Colour, Alignment and gitignore

### ISSUE THREAD

**Issue by evanwaltersdev** [evanwaltersdev/videos-hacktoberfest#51]

**Comment by unixfy** [comment]
Thanks - I will get around to doing it either tomorrow or this weekend :)

**Comment by evanwaltersdev** [comment]
> Thanks - I will get around to doing it either tomorrow or this weekend :)

Great! 👍

**Comment by unixfy** [comment]
Todo @unixfy 

- Write up a .gitignore

- Fix the colors in the footer

- Investigate and fix alignment issues

- Investigate fonts not loading

- Check mobile appearance
