### ISSUE TITLE
Write a lazyload script

### ISSUE THREAD

**Issue by unixfy** [evanwaltersdev/videos-hacktoberfest#80]
We need somebody to write a lazy-load script in JS for the videos page, as the sheer number of YouTube videos loading all at once (when the DOM loads) can cause crashing on some devices, and crashing is definitely not something we want.

Please submit a PR **referencing this issue** for review.

---

If you are not aware, a lazyloader is a script that causes certain elements in the DOM (in this case, YouTube videos) to only load when they enter the viewport, i.e. when they are scrolled to and visible on the client's display. 

Thanks.

**Comment by kemonrider** [comment]
I will do it

**Comment by unixfy** [comment]
Closed - #86
